blueprint:
  name: Switch PiSignage Playlist
  description: Change playlist on one or more PiSignage players.
  domain: automation
  input:
    player_entities:
      name: Player Entities
      description: Select one or more PiSignage player entities to control.
      selector:
        entity:
          multiple: true
          filter:
            - integration: pisignage
              domain: media_player
    playlist_source:
      name: Target Playlist
      description: The playlist to switch to.
      selector:
        select:
          options: >
            {% set options = [] %}
            {% for entity in device_entities('media_player') if 'pisignage' in entity %}
              {% if state_attr(entity, 'source_list') %}
                {% for source in state_attr(entity, 'source_list') %}
                  {% set options = options + [source] %}
                {% endfor %}
              {% endif %}
            {% endfor %}
            {{ options | unique | list }}

action:
  - repeat:
      for_each: "{{ input.player_entities }}"
      sequence:
        - service: media_player.select_source
          target:
            entity_id: "{{ repeat.item }}"
          data:
            source: "{{ input.playlist_source }}"