blueprint:
  name: Change Playlist on PiSignage Media Players
  description: A script to change the playlist on selected PiSignage media players. Check the 'source_list' attribute of your media player for available playlists.
  domain: script
  input:
    media_players:
      name: Media Players
      description: Select the PiSignage media players to control
      selector:
        entity:
          integration: pisignage  # Replace with your actual integration
          domain: media_player
          multiple: true
    playlist:
      name: Playlist
      description: The playlist to switch to (enter the exact name from the player's source list)
      selector:
        text:
sequence:
  - repeat:
      for_each: !input media_players
      sequence:
        - if:
            - condition: state
              entity_id: "{{ repeat.item }}"
              state: 'off'
          then:
            - service: media_player.turn_on
              target:
                entity_id: "{{ repeat.item }}"
        - service: media_player.select_source
          data:
            source: !input playlist
          target:
            entity_id: "{{ repeat.item }}"